### ISSUE TITLE
Google tasks?

### ISSUE THREAD

**Issue by niksingh710** [atiladefreitas/dooing#1]
This is a far-fetched request, and I would like to contribute to it if you feel like moving forward with this.

The [calendar](https://github.com/itchyny/calendar.vim) plugin supports Google Tasks and even Google Calendar.

However, there are a few nuances, such as tasks being fetched directly without caching, which makes accessing them slower. I feel that implementing a caching mechanism for the task list and enabling background syncing would improve the experience.

**Comment by atiladefreitas** [comment]
@niksingh710 Thank you for your question and for your willingness to help.

I didn't know about this plugin, but I think it's great.

I like the idea of ​​integrating it with other to-do lists and I think Google Tasks would be a great starting point.

I'm still thinking about a roadmap for this project, but I think that before thinking about integrating it with other to-do lists we should think about creating folders and improving the categories.

Because then it would be easier to integrate with Google Tasks, for example, by having a folder in the plugin just for it. Does that make any sense?

Buuutttt, nothing stops you from creating a fork and calling me for help.

and by the way, I still don't have experience in integrating Neovim plugins with external APIs

**Comment by niksingh710** [comment]
sry for the late response buddy, i got wrapped up in some work.
Yes, you are right having folder and organizing subsets of tasks should be a first priority as that will be helpful.

For the api access ig calender plugin reference should help in that manner.
